#!/usr/bin/env bash
# A bash script that displays information
#+ about our subdomains.


function audit_subdomain {
    local subdomain=$1
    local domain=$2
    local record_type=$(dig +short $subdomain.$domain | awk '{print toupper($1)}')
    local destination=$(dig +short $subdomain.$domain)

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    subdomain_list=("www" "lb-01" "web-01" "web-02")
else
    subdomain_list=("$subdomain")
fi

for sub in "${subdomain_list[@]}"
do
    audit_subdomain $sub $domain
done
