#!/usr/bin/env bash
# A bash script that displays information
#+ about our subdomains.


domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    subdomains=(www lb-01 web-01 web-02)
else
    subdomains=($subdomain)
fi

for subdomain in ${subdomains[@]}; do
    result=$(dig +short $subdomain.$domain)
    record=$(dig $subdomain.$domain | awk '/ANSWER SECTION:/{getline; split($1,b,"."); print $4}')
    if [ -z "$result" ]; then
        echo "The subdomain $subdomain is not defined for $domain"
    else
        echo "The subdomain $subdomain is a $record record and points to $result"
    fi
done
