#!/usr/bin/env bash
# A script that installs nginx and configures it to return
# the string 'Hello world!' when its root / receives a GET request

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello world!" > /var/www/html/index.html
service nginx start
