#!/usr/bin/env bash
# A script that installs nginx and configures it to return
# the string 'Hello world!' when its root / receives a GET request

# Update package repository
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

# Create a test page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Test Nginx configuration by querying it with curl
if curl -s http://localhost | grep -q "Hello World!"; then
	    echo "Nginx configured successfully"
    else
	        echo "Nginx configuration failed"
fi

