#!/usr/bin/env bash
# A script that gets backup for all databases

# Get today's date
date=$(date +%d-%m-%Y)

# Set the password for the root user
password=$1

# Dump all MySQL databases to backup.sql
sudo mysqldump -u root -p$password --all-databases > backup.sql

# Compress the backup.sql file to a tar.gz archive
tar -czvf $date.tar.gz backup.sql

# Remove the original backup.sql file
rm backup.sql

