#!/usr/bin/env bash
#Bash script that displays the processes whose name contain the word bash

pids=$(pgrep -f bash)

for pid in $pids
do
	process_name=$(ps -p "$pid" -o comm=)
	echo "$pid $process_name"
done
