#!/usr/bin/env bash
# Print and say hi at 9th iteration

count=1
while [ $count -le 10 ]
do
  if [ $count -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  ((count++))
done

