#!/usr/bin/env bash
#Say bad luck at 4th, goodluck at 8.

count=1
while [ $count -le 10 ]
do
  if [ $count -eq 4 ]; then
    echo "bad luck"
  elif [ $count -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((count++))
done

