#!/usr/bin/env bash
#A script that finds patterns

for file in *; do
    if [[ "$file" != ".*" ]]; then
        if [[ "$file" = *"-"* ]]; then
            echo "${file#*-}"
        else
            echo "$file"
        fi
    fi
done

