#!/usr/bin/env bash
## Script that  configures an Ubuntu server as follow:
##	localhost resolves to 127.0.0.2
##	facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2\tlocalhost\n8.8.8.8\t\tfacebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
